version: '3'
services:


  db:
    ports:
      - 5432:5432

  graphql:
    ports:
      - 5433:5433

  app:
    container_name: mobydq-app
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    volumes:
      - ./test-results:/reports/junit
    ports:
      - 80:3000
    command: "npm run ci-test-and-lint"
    environment:
      JEST_JUNIT_OUTPUT: "/reports/junit/js-test-results.xml"