version: '3'
services:

  db:
    container_name: dq-db
    restart: always
    image: dq-db
    build:
      context: .
      dockerfile: ./conf/db/Dockerfile
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "public"
    volumes:
      - ./db/data/:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - dq-network

  graphql-api:
    container_name: dq-graphql-api
    restart: always
    image: dq-graphql-api
    build:
      context: .
      dockerfile: ./conf/graphql-api/Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL="postgres://postgres:password@db:5432/data_quality"
    command: ["postgraphile", "--connection", $DATABASE_URL, "-n", "0.0.0.0", "--schema", "base"]
    ports:
      - 5000:5000
    links:
      - db
    networks:
      - dq-network

  rest-api:
    container_name: dq-rest-api
    restart: always
    image: dq-rest-api
    build:
      context: .
      dockerfile: ./conf/api/Dockerfile
    depends_on:
      - graphql-api
      - db
    stdin_open: true
    tty: true
    volumes:
      - ./api/:/var/www/
    ports:
      - "5001:5001"
    networks:
      - dq-network

networks:
  dq-network:
    driver: bridge
