version: '3'
services:

  db:
    container_name: data-quality-db
    restart: always
    image: data-quality-db
    build:
      context: ./db
    volumes:
      - ./db/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"  # To be moved to environment file
      POSTGRES_DATABASE: "public"
    ports:
      - 5432:5432
    networks:
      - data-quality-network

  graphql:
    container_name: data-quality-graphql
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/data_quality" # To be moved to environment file
    command: ["postgraphile", "--connection", $DATABASE_URL, "--host", "0.0.0.0", "--schema", "base"]
    ports:
      - 5000:5000
    links:
      - db
    networks:
      - data-quality-network

  scripts:
    container_name: data-quality-scripts
    restart: always
    image: data-quality-scripts
    build:
      context: ./scripts
    volumes:
       - ./scripts:/srv/scripts
    tty: true
    depends_on:
      - graphql
    links:
      - graphql
    ports:
      - 5001:5001
    networks:
      - data-quality-network

  api:
    container_name: data-quality-api
    restart: always
    image: data-quality-api
    build:
      context: ./api
    volumes:
      - ./api:/srv/api/
    depends_on:
      - graphql
    links:
      - graphql
    ports:
      - 5002:5002
    networks:
      - data-quality-network

networks:
  data-quality-network:
