version: '3'
services:
  app:
    image: mobydq-app-dev
    build:
      dockerfile: Dockerfile-dev
      context: ./app

  app-test:
    container_name: mobydq-test-app
    build:
      context: ./app
      dockerfile: Dockerfile-test
    env_file:
      - ./.env
    command: "npm run test && npm run lint"
    image: mobydq-test-app
