version: '3.1'
services:


  db:
    ports:
      - 5432:5432

  api:
    volumes:
      - ./api/init:/srv/api/
    environment:
      FLASK_DEBUG: 1

  scripts:
    volumes:
       - ./scripts/init:/srv/scripts
    tty: true

  app:
    volumes:
      - ./app/src:/usr/src/app/src:ro
      - ./app/public:/usr/src/app/public:ro
    ports:
      - 5499:3000
