version: '3.1'
services:
  graphql:
    expose:
      - 5433
    ports:
      - 5433:5433

  api:
    volumes:
      - ./api/init:/srv/api/
    environment:
      FLASK_DEBUG: 1

  app:
    volumes:
      - ./app/init/public:/srv/app/public
      - ./app/init/src:/srv/app/src
    command: ["dev"]
  
  nginx:
    ports:
      - 8080:8080

  scripts:
    volumes:
      - ./scripts/init:/srv/scripts
    tty: true