version: '3'
services:

  db:
    container_name: dq-db
    restart: always
    build:
      context: .
      dockerfile: ./conf/db/Dockerfile
    image: dq-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "your_database"
    ports:
      - "5433:5432"
    networks:
      - dq-network
    
    
networks:
  dq-network:
    driver: bridge