version: '3'
services:

  db:
    container_name: data-quality-db
    restart: always
    image: data-quality-db
    build:
      context: ./db
    volumes:
      - data-quality-db-volume:/var/lib/postgresql/data
    env_file:
        - ./.env
    ports:
      - 5432:5432
    networks:
      - default
      
  graphql:
    container_name: data-quality-graphql
    restart: always
    image: graphile/postgraphile
    env_file:
      - ./.env 
    ports:
      - 5433:5433
    depends_on:
      - db
    links:
      - db
    networks:
      - default
    command: ["postgraphile", "--cors", "--connection", "${DATABASE_URL}", "--host", "0.0.0.0", "--port", "5433", "--schema", "base"]    
      
  api:
    container_name: data-quality-api
    restart: always
    image: data-quality-api
    build:
      context: ./api
    volumes:
      - $API_VOLUME_PATH:/srv/api/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      FLASK_APP: init/api.py
      FLASK_RUN_PORT: 5434
    ports:
      - 5434:5434
    depends_on:
      - graphql
    links:
      - graphql
    networks:
      - default
    command: ["flask", "run", "--host=0.0.0.0"]
    
  scripts:
    container_name: data-quality-scripts
    restart: always
    image: data-quality-scripts
    build:
      context: ./scripts
      args:
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_SENDER=${MAIL_SENDER}
    env_file:
      - ./.env
    volumes:
       - $SCRIPT_VOLUME_PATH:/srv/scripts
    depends_on:
      - graphql
    links:
      - graphql
    networks:
      - default
            
  app-dev:
    container_name: data-quality-app-dev
    restart: always
    image: data-quality-app-dev
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    volumes:
      - $APP_VOLUME_PATH:/usr/src/app
    env_file:
      - ./.env
    expose:
      - 5499
    ports:
      - 5499:3000
    depends_on:
      - api
      - graphql
    links:
      - api
      - graphql
    networks:
      - default
      
  app-prod:
    container_name: data-quality-app-prod
    build:
      context: ./app
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'
      
networks:
  default:
    external:
      name: data-quality-network

volumes:
  data-quality-db-volume:
    external: true