version: '3'
services:

  db:
    container_name: data-quality-db
    restart: always
    image: data-quality-db
    build:
      context: ./db
    volumes:
      - ./db/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # To be moved to environment file
      POSTGRES_DATABASE: public
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - data-quality-network

  graphql:
    container_name: data-quality-graphql
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/data_quality # To be moved to environment file
    expose:
      - 5433
    ports:
      - 5433:5433
    command: ["postgraphile", "--connection", $DATABASE_URL, "--host", "0.0.0.0", "--port", "5433", "--schema", "base"]
    links:
      - db
    networks:
      - data-quality-network

  scripts:
    container_name: data-quality-scripts
    restart: always
    image: data-quality-scripts
    build:
      context: ./scripts
    volumes:
       - ./scripts:/srv/scripts
    expose:
      - 5434
    ports:
      - 5434:5434
    tty: true
    depends_on:
      - graphql
    links:
      - graphql
    networks:
      - data-quality-network

  api:
    container_name: data-quality-api
    restart: always
    image: data-quality-api
    build:
      context: ./api
    volumes:
      - ./api:/srv/api/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      FLASK_APP: api.py
      FLASK_RUN_PORT: 5435
      FLASK_DEBUG: 1
    expose:
      - 5435
    ports:
      - 5435:5435
    command: ["flask", "run", "--host=0.0.0.0"]
    depends_on:
      - scripts
    links:
      - graphql
    networks:
      - data-quality-network

networks:
  data-quality-network:
