version: "3.1"
services:
    db-cloudera:
        container_name: mobydq-test-db-cloudera
        image: mobydq-test-db-cloudera
        restart: always
        build:
            context: ./test/db-cloudera/
            dockerfile: Dockerfile
        expose:
            - 10000
        hostname: quickstart.cloudera
        privileged: true
        tty: true

    db-hortonworks:
        container_name: mobydq-test-db-hortonworks
        image: mobydq-test-db-hortonworks
        restart: always
        build:
            context: ./test/db-hortonworks/
            dockerfile: Dockerfile
        expose:
            - 10000
        hostname: sandbox-hdf.hortonworks.com
        privileged: true
        tty: true

    db-mariadb:
        container_name: mobydq-test-db-mariadb
        image: mobydq-test-db-mariadb
        restart: always
        build:
            context: ./test/db-mariadb/
            dockerfile: Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: "1234"
        expose:
            - 3306

    db-mysql:
        container_name: mobydq-test-db-mysql
        image: mobydq-test-db-mysql
        restart: always
        build:
            context: ./test/db-mysql/
            dockerfile: Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: "1234"
        expose:
            - 3306

    db-oracle:
        container_name: mobydq-test-db-oracle
        image: mobydq-test-db-oracle
        restart: always
        build:
            context: ./test/db-oracle/
            dockerfile: Dockerfile
        environment:
            ORACLE_PWD: "1234-abcd"
        expose:
            - 1521

    db-postgresql:
        container_name: mobydq-test-db-postgresql
        image: mobydq-test-db-postgresql
        restart: always
        build:
            context: ./test/db-postgresql/
            dockerfile: Dockerfile
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
            POSTGRES_DATABASE: "star_wars"
        expose:
            - 5432

    db-sql-server:
        container_name: mobydq-test-db-sql-server
        image: mobydq-test-db-sql-server
        restart: always
        build:
            context: ./test/db-sql-server/
            dockerfile: Dockerfile
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "1234-abcd"
        expose:
            - 1433

    test-scripts:
        container_name: mobydq-test-scripts
        image: mobydq-test-scripts
        build:
            context: .
            dockerfile: ./test/Dockerfile
        command: ["./run-tests.sh", "${TEST_CASE}", "${TEST_HOST}", "${TEST_PORT}"]
        depends_on:
          - db
          - graphql

    test-lint-python:
        container_name: mobydq-test-lint-python
        image: mobydq-test-lint-python
        build:
            context: .
            dockerfile: ./test/Dockerfile
        command: ["pylint", "scripts", "test"]
