version: '3'
services:

  db:
    container_name: dq-db
    restart: always
    image: dq-db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "public"
    volumes:
      - ./db/data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dq-network

  graphql:
    container_name: dq-graphql
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/data_quality"
    command: ["postgraphile", "--connection", $DATABASE_URL, "--host", "0.0.0.0", "--schema", "base"]
    ports:
      - 5000:5000
    links:
      - db
    networks:
      - dq-network

  api:
    container_name: dq-api
    restart: always
    image: dq-api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - graphql
      - db
    stdin_open: true
    tty: true
    volumes:
      - ./api/:/srv/api/
    ports:
      - 5001:5001
    networks:
      - dq-network

networks:
  dq-network:
    driver: bridge
