version: '3'
services:


  api:
    volumes:
      - ./api:/srv/api/
    environment:
      FLASK_DEBUG: 1

  scripts:
    volumes:
       - ./scripts:/srv/scripts
    tty: true

  app:
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    volumes:
      - ./app:/usr/src/app
    ports:
      - 5499:3000
