version: '3'
services:
  api:
    container_name: dq-api
    restart: always
#    env_file:
#      - ./.env
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./conf/api/dockerfile
    image: dq-api
    stdin_open: true
    tty: true
    volumes:
      - /Projects/:/var/www/
    ports:
      - "5001:5001"
    networks:
      - dq-network
  db:
    container_name: dq-db
    restart: always
    build:
      context: .
      dockerfile: ./conf/db/Dockerfile
    image: dq-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "your_database"
#    volumes: 
#      - /Projects/data-quality/db-data/:/var/lib/postgresql
    ports:
      - "5433:5432"
    networks:
      - dq-network
  postgraphile:     
    container_name: postg-api
    restart: always
    image: graphile/postgraphile
#    build: 
#      context: .
#      dockerfile: ./conf/pgf/Dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/data_quality"
      DATABASE_SCHEMA: "base"
      NODE_ENV: "production"
      PROD: "true"
    command: ["postgraphile", "-c", $DATABASE_URL, "-n", "0.0.0.0", "--schema", "base"]
    ports:
      - 5000:5000
    links:
      - db
    networks:
      - dq-network
networks:
  dq-network:
    driver: bridge