# .circleci/config.yml
version: 2
jobs:

  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Install Python 3 environment
          command: |
            sudo apt-get install software-properties-common
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt-get update
            sudo apt-get install python3.6
            sudo apt-get install python3-pip

      - run:
          name: Install Python dependencies
          command: |
            sudo python3.6 --version
            sudo pip3 install --upgrade pip
            sudo pip3 install -r api/init/requirements.txt
            sudo pip3 install -r scripts/init/requirements.txt
            sudo pip3 install nose2

      - run:
          name: Create configuration file
          command: |
            echo "[graphql]" >> ./scripts/init/scripts.cfg
            echo "url = http://0.0.0.0:5433/graphql" >> ./scripts/init/scripts.cfg

      - run:
          name: Run tests
          command: |
            echo 'export PYTHONPATH=./test:$PYTHONPATH' >> $BASH_ENV
            echo 'export PYTHONPATH=./api/init:$PYTHONPATH' >> $BASH_ENV
            echo 'export PYTHONPATH=./scripts/init:$PYTHONPATH' >> $BASH_ENV
            source $BASH_ENV
            sudo source dq/bin/activate
            docker ps -a
            nose2 --plugin nose2.plugins.junitxml --junit-xml -v

      - store_artifacts:
          path: test/junit/test-results.xml
          destination: test-results

      - store_test_results:
          path: test
